version: "3.8"

services:
  db:
    image: postgres:13
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jilvo -d db_django_b_b" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/b_b_copy/.env

volumes:
  postgres_data:
